name: saha
description: تطبيق Flutter محلي لحجز الملاعب والتحديات وتمارين الشارع ومسارات المشي مع حساب صحي وقصص محترفين.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.3
  iconly: ^1.0.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/seed/venues.json
    - assets/seed/events.json
    - assets/seed/users.json
    - assets/seed/stories.json
    - assets/seed/fields.json
    - assets/seed/catalog.json
    - assets/images/
    - assets/icons/
