name: saha
description: تطبيق Flutter محلي لحجز الملاعب والتحديات وتمارين الشارع ومسارات المشي مع حساب صحي وقصص محترفين.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  collection: ^1.18.0
  google_fonts: ^6.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/seed/venues.json
    - assets/seed/events.json
    - assets/seed/users.json
    - assets/seed/stories.json
    - assets/seed/fields.json
    - assets/images/
    - assets/icons/
